tailwind.config = {
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface-variant": "#353534",
        "surface-container": "#201f1f",
        "outline": "#aa8a7d",
        "on-tertiary-fixed": "#001d35",
        "inverse-primary": "#a33e00",
        "on-primary": "#000000",
        "primary-fixed-dim": "#FF6600",
        "background": "#131313",
        "secondary": "#c8c6c5",
        "surface-bright": "#393939",
        "on-tertiary": "#003256",
        "error-container": "#93000a",
        "surface-dim": "#131313",
        "surface-container-lowest": "#0e0e0e",
        "on-surface": "#e5e2e1",
        "on-error": "#690005",
        "tertiary-fixed": "#d0e4ff",
        "on-error-container": "#ffdad6",
        "error": "#ffb4ab",
        "on-surface-variant": "#e3bfb1",
        "on-background": "#e5e2e1",
        "secondary-fixed": "#e5e2e1",
        "on-secondary-fixed-variant": "#474746",
        "primary-container": "#ff6600",
        "secondary-fixed-dim": "#c8c6c5",
        "tertiary-fixed-dim": "#9ccaff",
        "tertiary-container": "#009cfc",
        "surface-container-high": "#2a2a2a",
        "on-tertiary-container": "#003155",
        "inverse-on-surface": "#313030",
        "on-secondary-container": "#b7b5b4",
        "surface": "#131313",
        "secondary-container": "#474746",
        "on-primary-container": "#000000",
        "outline-variant": "#5a4136",
        "surface-tint": "#FF6600",
        "primary": "#FF6600",
        "on-primary-fixed-variant": "#7c2e00",
        "inverse-surface": "#e5e2e1",
        "tertiary": "#9ccaff",
        "primary-fixed": "#ffdbcd",
        "on-secondary": "#303030",
        "surface-container-highest": "#353534",
        "on-secondary-fixed": "#1b1c1c",
        "on-tertiary-fixed-variant": "#00497b",
        "on-primary-fixed": "#000000",
        "surface-container-low": "#1c1b1b",
        "monero-gray": "#4d4d4d",
      },
      fontFamily: {
        headline: ['"Space Grotesk"', "sans-serif"],
        body: ['"Inter"', "sans-serif"],
        label: ['"JetBrains Mono"', "monospace"],
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        sm: "0.125rem",
        md: "0.375rem",
        lg: "0.25rem",
        xl: "0.5rem",
        "2xl": "0.75rem",
        full: "9999px",
      },
    },
  },
};
